### ISSUE TITLE
"Failed to get screenshot"

### ISSUE THREAD

**Issue by rubisco13** [Julioevm/tiny-scraper#2]
Hi, trying this out on my RG5XXH running the 20240905 cbepx-me modded stockos. 

When I run this it does not download any of the images. Attached is the log, I also used the following for my config.json file: 

{
    "user": "my_user",
    "password": "my_password",
    "media_type": "box-2d",
    "region": "us
"
}

[log.txt](https://github.com/user-attachments/files/17169237/log.txt)

I hope this is just an issue I'm making, very much looking forward to this!

**Comment by Julioevm** [comment]
It could be because those games don't have available  "box-2d" media type. I see a lot of cases of pokemon romhacks, those don't have media in the database I'm afraid. For the rest, check if using "ss" works for media_type.

And make sure the "us" has the quotes properly closing the word in the config, I think thats just a typo from pasting it here...

**Comment by rubisco13** [comment]
Thank you for the quick response! After some tinkering I've discovered the issue was that I had box-2d not box-2D. Totally fixed. I knew I'd have to do hacks manually, I have a file I keep on my hard drive for this reason.

This is such a great tool! So happy to finally have box art after all this time - stockos staying superior. Thanks so much!
